# Global Vars:
WIDE_RANGE = True

if WIDE_RANGE: # Wide scene parameters
    #Tracker:
    TRACKER_SEARCH_WINDOW = 2
    TRACKER_SIGMA_FACTOR = 0.125
    TRACKER_INTERP_FACTOR = 0.075
    TRACKER_SIGMA = 0.2

    #Detection:
    ABSDIFF_THRESHOLD = 25
    PERSON_ASPECT_RATIO = 1.5
    ALPHA_BLENDING = 0.00
    CLOSING_KERNEL = (50, 20)
    MARGINS_IGNORANCE_TO_DETECT = 20
    MARGINS_IGNORANCE_TO_DECISION = 5
    MIN_BLOB_AREA = 500




else:# Narrow scene parameters
    # Tracker:
    TRACKER_SEARCH_WINDOW = 4
    TRACKER_SIGMA_FACTOR = 0.125
    TRACKER_INTERP_FACTOR = 0.075
    TRACKER_SIGMA = 0.2

    # Detection:
    ABSDIFF_THRESHOLD = 25
    PERSON_ASPECT_RATIO = 1.5
    ALPHA_BLENDING = 0.0
    CLOSING_KERNEL = (50, 20)
    MARGINS_IGNORANCE = 10
    MIN_BLOB_AREA = 500

